import UserInfo from "../../components/UserInfo/UserInfo";

const Home = () => {
    return (
        <div className="flex flex-row">
            <UserInfo />
            <p className="mx-10">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus cumque veniam quis enim, sint laboriosam? Mollitia voluptatem voluptatum sunt quae laborum illum doloremque, incidunt eum eaque excepturi quas asperiores corporis pariatur deleniti velit delectus alias eos nisi illo possimus in quibusdam error? Sunt maiores dolore hic placeat exercitationem, ducimus illo distinctio expedita facilis iure quod rerum at natus laudantium? Dignissimos corrupti eaque commodi veniam temporibus, laudantium nemo ipsa iusto voluptate quas vitae molestias doloribus impedit id aliquid repellendus esse aperiam? Consequatur dolorem, quo officia corporis blanditiis aspernatur reiciendis, perferendis odio totam provident laborum minus quisquam eius quidem, laboriosam optio molestias.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus cumque veniam quis enim, sint laboriosam? Mollitia voluptatem voluptatum sunt quae laborum illum doloremque, incidunt eum eaque excepturi quas asperiores corporis pariatur deleniti velit delectus alias eos nisi illo possimus in quibusdam error? Sunt maiores dolore hic placeat exercitationem, ducimus illo distinctio expedita facilis iure quod rerum at natus laudantium? Dignissimos corrupti eaque commodi veniam temporibus, laudantium nemo ipsa iusto voluptate quas vitae molestias doloribus impedit id aliquid repellendus esse aperiam? Consequatur dolorem, quo officia corporis blanditiis aspernatur reiciendis, perferendis odio totam provident laborum minus quisquam eius quidem, laboriosam optio molestias.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus cumque veniam quis enim, sint laboriosam? Mollitia voluptatem voluptatum sunt quae laborum illum doloremque, incidunt eum eaque excepturi quas asperiores corporis pariatur deleniti velit delectus alias eos nisi illo possimus in quibusdam error? Sunt maiores dolore hic placeat exercitationem, ducimus illo distinctio expedita facilis iure quod rerum at natus laudantium? Dignissimos corrupti eaque commodi veniam temporibus, laudantium nemo ipsa iusto voluptate quas vitae molestias doloribus impedit id aliquid repellendus esse aperiam? Consequatur dolorem, quo officia corporis blanditiis aspernatur reiciendis, perferendis odio totam provident laborum minus quisquam eius quidem, laboriosam optio molestias.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus cumque veniam quis enim, sint laboriosam? Mollitia voluptatem voluptatum sunt quae laborum illum doloremque, incidunt eum eaque excepturi quas asperiores corporis pariatur deleniti velit delectus alias eos nisi illo possimus in quibusdam error? Sunt maiores dolore hic placeat exercitationem, ducimus illo distinctio expedita facilis iure quod rerum at natus laudantium? Dignissimos corrupti eaque commodi veniam temporibus, laudantium nemo ipsa iusto voluptate quas vitae molestias doloribus impedit id aliquid repellendus esse aperiam? Consequatur dolorem, quo officia corporis blanditiis aspernatur reiciendis, perferendis odio totam provident laborum minus quisquam eius quidem, laboriosam optio molestias.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus cumque veniam quis enim, sint laboriosam? Mollitia voluptatem voluptatum sunt quae laborum illum doloremque, incidunt eum eaque excepturi quas asperiores corporis pariatur deleniti velit delectus alias eos nisi illo possimus in quibusdam error? Sunt maiores dolore hic placeat exercitationem, ducimus illo distinctio expedita facilis iure quod rerum at natus laudantium? Dignissimos corrupti eaque commodi veniam temporibus, laudantium nemo ipsa iusto voluptate quas vitae molestias doloribus impedit id aliquid repellendus esse aperiam? Consequatur dolorem, quo officia corporis blanditiis aspernatur reiciendis, perferendis odio totam provident laborum minus quisquam eius quidem, laboriosam optio molestias.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus cumque veniam quis enim, sint laboriosam? Mollitia voluptatem voluptatum sunt quae laborum illum doloremque, incidunt eum eaque excepturi quas asperiores corporis pariatur deleniti velit delectus alias eos nisi illo possimus in quibusdam error? Sunt maiores dolore hic placeat exercitationem, ducimus illo distinctio expedita facilis iure quod rerum at natus laudantium? Dignissimos corrupti eaque commodi veniam temporibus, laudantium nemo ipsa iusto voluptate quas vitae molestias doloribus impedit id aliquid repellendus esse aperiam? Consequatur dolorem, quo officia corporis blanditiis aspernatur reiciendis, perferendis odio totam provident laborum minus quisquam eius quidem, laboriosam optio molestias.</p>

        </div>
    )
}

export default Home;